# Generated by Django 4.0.3 on 2022-05-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0002_rename_name_about_first_name_about_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('duration', models.TextField()),
            ],
        ),
    ]
