# Generated by Django 4.0.3 on 2022-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0003_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
