# Generated by Django 4.0.3 on 2022-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0004_experience_description_alter_experience_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
