# Generated by Django 4.0.3 on 2022-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0006_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_img', models.CharField(max_length=100)),
                ('skill_title', models.CharField(max_length=100)),
                ('skill_knowledge_title', models.CharField(max_length=100)),
                ('skill_knowledge', models.CharField(max_length=100)),
            ],
        ),
    ]
