# Generated by Django 4.0.3 on 2022-06-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0007_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
