# Generated by Django 4.0.3 on 2022-06-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0008_alter_skill_skill_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_knowledge',
            new_name='skill_knowledge_1',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_img',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_knowledge_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_knowledge_3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_knowledge_4',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
