# Generated by Django 4.0.3 on 2022-06-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0009_rename_skill_knowledge_skill_skill_knowledge_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
    ]
